build: strip files

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -23,6 +23,8 @@ WORKDIR /tmp/ngtcp2-build
 # Install build dependencies and download ngtcp2 source code
 RUN set -x && \
     apk add --no-cache --virtual .build-deps \
+      # For strip command to reduce binary size
+      binutils \
       build-base \
       curl \
       openssl-dev \
@@ -45,6 +47,9 @@ RUN set -x && \
     make -j "$(nproc)" && \
     make install
 
+# Strip libraries
+RUN find /usr/local/lib -type f -name "*.so*" -exec strip --strip-unneeded {} +
+
 # -----------------------------------------------------------------------------------------------
 
 # Set Alpine as the base image for building Unbound
@@ -65,6 +70,8 @@ WORKDIR /tmp/unbound-build
 # Install build dependencies and download unbound source code
 RUN set -x && \
     apk add --no-cache --virtual .build-deps \
+      # For strip command to reduce binary size
+      binutils \
       build-base \
       curl \
       expat-dev \
@@ -129,6 +136,17 @@ RUN set -x && \
     # Compile and install Unbound
     make -j "$(nproc)" && \
     make install
+
+# Cleanup unused files and reduce binary size
+RUN rm -rf /opt/unbound/include \
+           /opt/unbound/share \
+           /opt/unbound/lib/pkgconfig \
+           /opt/unbound/lib/*.la && \
+    # Strip binaries
+    # Ignore errors --> unbound-control-setup is a script
+    strip /opt/unbound/sbin/* > /dev/null 2>&1 || true && \
+    # Strip libraries
+    find /opt/unbound/lib -type f -name "*.so*" -exec strip --strip-unneeded {} +
 
 # Set workdir to var
 WORKDIR /var/unbound
@@ -204,13 +222,10 @@ COPY --from=unbound-build --chown="${UNBOUND_USER_UID}:${UNBOUND_USER_GID}" /etc
 COPY --from=unbound-build --chown="${UNBOUND_USER_UID}:${UNBOUND_USER_GID}" /var/unbound /var/unbound
 
 # Copy the ngtcp2 library files, header files not needed at runtime
-COPY --from=ngtcp2-build /usr/local/lib /usr/local/lib
+COPY --from=ngtcp2-build /usr/local/lib/libngtcp2*.so* /usr/local/lib
 
-# Copy Files
-COPY --chown="${UNBOUND_USER_UID}:${UNBOUND_USER_GID}" files /files
-
-# Set permissions for Unbound scripts
-RUN chmod +x /files/scripts/*.sh
+# Copy Files and set permissions (/files/scripts/*.sh need to be executable)
+COPY --chown="${UNBOUND_USER_UID}:${UNBOUND_USER_GID}" --chmod=755 files /files
 
 # Set build date argument here, because caching would break otherwise
 # It is set during the build process in the reusable workflow
